add TestAli and PageTestAli
Znamm9/justAutomationFramework pull request #6
Opened 2021-02-02 14:45 UTC by eltess

2021-02-02 14:49 UTC, StepaniukAndii requested changes

2021-02-02 14:49 UTC, StepaniukAndii commented on src/test/java/PageAliExpres.java
> +
empty line

2021-02-02 14:49 UTC, StepaniukAndii commented on src/test/java/PageAliExpres.java
> +
@eltess

2021-02-02 14:49 UTC, StepaniukAndii commented on src/test/java/TestAliExpres.java
> +
empty line @eltess

2021-02-02 14:49 UTC, StepaniukAndii commented on src/test/java/TestAliExpres.java
> +
empty line @eltess

2021-02-03 08:08 UTC, Znamm9 requested changes

2021-02-03 08:08 UTC, Znamm9 commented on src/test/java/PageAliExpres.java
> +    public WebElement serchFild() {
All field that returns elements should start from get
```suggestion
    public WebElement getSerchFild() {
```

2021-02-03 08:08 UTC, Znamm9 commented on src/test/java/PageAliExpres.java
> +        return findElement ("//input[@id='search-form__input']");
remove spaces before method parenthesis
```suggestion
        return findElement("//input[@id='search-form__input']");
```

2021-02-03 08:08 UTC, Znamm9 commented on src/test/java/TestAliExpres.java
> +    public void startTest() {
remove parenthesis and pun name that displays what actually you do in the test
```suggestion
    public void searchForrefrigerators(){
```

2021-02-03 08:08 UTC, Znamm9 commented on src/test/java/PageAliExpres.java
> +public class PageAliExpres extends BasePage {
which exactly page? AliExpres is a site but not a page. Use a clearer name, please
```suggestion
public class AliHomePage extends BasePage{
```

2021-02-03 08:08 UTC, Znamm9 commented on src/test/java/TestAliExpres.java
> +        pageAliExpres.serchFild ().sendKeys ("холодильник");
remove spaces
```suggestion
        PageAliExpres pageAliExpres = new PageAliExpres(driver);
        openUrl("https://allo.ua/ru/kompjutery/");
        pageAliExpres.serchFild().click();
        pageAliExpres.serchFild().sendKeys("холодильник");
```

2021-02-03 08:08 UTC, Znamm9 commented on src/test/java/PageAliExpres.java
> +    public PageAliExpres(WebDriver driver) {
remove spaces
```suggestion
    public PageAliExpres(WebDriver driver){
```

2021-02-03 13:16 UTC, eltess commented
Addd new folder

2021-02-03 14:03 UTC, eltess commented
дщщ

2021-02-03 14:10 UTC, Johasan commented on src/test/java/AliExpres/PageAliExpres.java
> +
Delete space

2021-02-03 14:11 UTC, Johasan commented on src/test/java/AliExpres/TestAliExpres.java
> +
Delete space

2021-02-03 14:23 UTC, eltess reviewed
check my new  folder

2021-02-03 14:23 UTC, eltess commented on src/test/java/AliExpres/TestAliExpres.java
> +
Ok man

2021-02-03 14:27 UTC, Johasan approved these changes

2021-02-03 14:31 UTC, StepaniukAndii approved these changes

2021-02-04 17:24 UTC, closed without merging